### ISSUE TITLE
win 10  64位系统 无法用

### ISSUE THREAD

**Issue by chenxun450** [qianniancn/go-dmsoft#1]
直接调用example，出现错误1 ： **在调用dmreg.dll时，显示 不是有效win32程序。**

在注释掉下面的代码后。采用手动regsvr32 dm.dll后
```
         // 这里是免注册方式
	//fmt.Println(dir)
	//dmsoft.SetDllPathW(dir+"\\dm.dll", 0)
```
出现错误2： 下面这行代码报错，显示   **panic:  没有注册类**

`com.IUnknown, err = oleutil.CreateObject("dm.dmsoft")`

请问下您的运行环境是啥样的

**Comment by qianniancn** [comment]
我更新过示例文件了
然后win64编译或运行 需要设置，命令行执行这个
`export GOARCH=386`

**Comment by qianniancn** [comment]
或者在用户变量里面设置GOARCH值为386

**Comment by chenxun450** [comment]
> 我的也是win64，因为大漠插件是win32的，然后win64编译或运行 需要设置，命令行执行这个
> `export GOARCH=386`

谢谢答复。 成功执行了

哈哈，windows 是 set GOARCH=386
