### ISSUE TITLE
大佬们，怎么判断角色的血量呢

### ISSUE THREAD

**Issue by lilei10101010** [qianniancn/go-dmsoft#11]
比如说，血量100，当掉了20血的时候，自动加血，不掉血/满血的时候，不用点加血。

还有个问题，大漠需要管理员权限才能执行，我现在每次改下代码就go build main.go把它编译成exe文件才能执行，可不可以不编译直接go run main.go就用管理员权限执行呢

**Comment by qianniancn** [comment]
血量的话识别数字吧

> 还有个问题，大漠需要管理员权限才能执行，我现在每次改下代码就go build main.go把它编译成exe文件才能执行，可不可以不编译直接go run main.go就用管理员权限执行呢

给编辑器管理员权限就可以了

**Comment by lilei10101010** [comment]
多谢大佬，回去尝试下
