### ISSUE TITLE
大漠dllAPI部分缺少得问题

### ISSUE THREAD

**Issue by aishuaikang** [qianniancn/go-dmsoft#12]
希望完善，谢谢大佬

**Comment by aishuaikang** [comment]
// func (com *DmSoft)FindPicMem(x1, y1, x2, y2, pic_info, delta_color,sim, dir,intX, intY)  int{}
// func (com *DmSoft)FindPicMemE(x1, y1, x2, y2, pic_info, delta_color,sim, dir,intX, intY)  string{}
// func (com *DmSoft)FindPicMemEx(x1, y1, x2, y2, pic_info, delta_color,sim, dir,intX, intY)  string{}
// func (com *DmSoft)FindShape(x1, y1, x2, y2, offset_color,sim, dir,intX,intY) int{}
// func (com *DmSoft)FindShapeE(x1, y1, x2, y2, offset_color,sim, dir,intX,intY) string{}
// func (com *DmSoft)FindShapeEx(x1, y1, x2, y2, offset_color,sim, dir,intX,intY) string{}
// func (com *DmSoft)FreePic(pic_name) int{}
// func (com *DmSoft)GetScreenData(x1, y1, x2, y2) int{}
// func (com *DmSoft)GetScreenDataBmp(x1,y1,x2,y2,data,size) int{}
// func (com *DmSoft)ImageToBmp(pic_name,bmp_name) int{}
// func (com *DmSoft)LoadPic(pic_name) int{}
// func (com *DmSoft)LoadPicByte(addr,size,pic_name) int{}
// func (com *DmSoft)LoadPic(pic_name) int{}

**Comment by qianniancn** [comment]
这些并不常用吧，你可以自己添加然后提交一个pr

**Comment by aishuaikang** [comment]
> 这些并不常用吧，你可以自己添加然后提交一个pr

试过了 pr扔进去后 并没拿到需要的值

**Comment by qianniancn** [comment]
后缀是E，是针对易语言的API

**Comment by aishuaikang** [comment]
> // func (com *DmSoft)GetScreenDataBmp(x1,y1,x2,y2,data,size) int{}

其实用到的就这写
// func (com *DmSoft)FreePic(pic_name) int{}
// func (com *DmSoft)GetScreenData(x1, y1, x2, y2) int{}
// func (com *DmSoft)GetScreenDataBmp(x1,y1,x2,y2,data,size) int{}
// func (com *DmSoft)ImageToBmp(pic_name,bmp_name) int{}
// func (com *DmSoft)LoadPic(pic_name) int{}
// func (com *DmSoft)LoadPicByte(addr,size,pic_name) int{}
// func (com *DmSoft)LoadPic(pic_name) int{}
对桌面截图以及图片的处理

**Comment by qianniancn** [comment]
下次添加一下吧

**Comment by aishuaikang** [comment]
> 下次添加一下吧

跪谢

**Comment by qianniancn** [comment]
添加好了

```go
	var data, size int
	dm.GetScreenDataBmp(0, 0, 800, 800, &data, &size)
	bs := *(*[]byte)(unsafe.Pointer(&_bytes{
		data,
		size,
	}))
	os.WriteFile("test.bmp", bs, os.ModePerm)
```

**Comment by aishuaikang** [comment]
> 

爱你
