### ISSUE TITLE
Dmsoft not declared by package dmsoft 的问题

### ISSUE THREAD

**Issue by aishuaikang** [qianniancn/go-dmsoft#13]
在更新了最新版后
![WX20230111-120035@2x](https://user-images.githubusercontent.com/68257609/211715026-966d0dea-ab53-4a62-bef8-a0c0ba5ecaf4.png)
出现 Dmsoft not declared by package dmsoft;
git clone 后源码中也同样出现这种问题

**Comment by qianniancn** [comment]
他是找不到这个，你要和整个项目一起打开

**Comment by aishuaikang** [comment]
> 他是找不到这个，你要和整个项目一起打开

我是用 go get方式安装的，您的意思是我要把源码下载下来放到项目目录是嘛

**Comment by qianniancn** [comment]
你就把整个项目git clone 到自己电脑上，然后打开整个项目

**Comment by aishuaikang** [comment]
> 你就把整个项目git clone 到自己电脑上，然后打开整个项目

懂了

**Comment by qianniancn** [comment]
go get 估计缓存没更新，用下面的拉去
`go get -u github.com/qianniancn/go-dmsoft@master`

**Comment by aishuaikang** [comment]
<img width="785" alt="image" src="https://user-images.githubusercontent.com/68257609/211718518-ae207370-2b88-407a-b427-b8d44cbde87f.png">
您可以看下 ，我已经把源码clone 到我的项目目录，还是报错

**Comment by qianniancn** [comment]
这样是不行的，项目目录结构不用改

**Comment by aishuaikang** [comment]
我已经知道根本原因了。
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/68257609/211718749-3cbb31e7-da3c-4e31-b65f-500ed0a73851.png">
这些注释影响了golang的语法解析导致报错的

**Comment by qianniancn** [comment]
把dll 放到cmd文件夹就行
