### ISSUE TITLE
如何调用

### ISSUE THREAD

**Issue by sangluyuan** [qianniancn/go-dmsoft#2]
我在main.go 里创建 了dm 对象， 在同包的其他 go文件中如何 使用 创建的对象

**Comment by qianniancn** [comment]
首字母大写就会导出，在其他文件中就可以调用了，实在不会，晚一点我写一个例子

**Comment by sangluyuan** [comment]
你的QQ 是多少，方便交流

**Comment by qianniancn** [comment]
@sangluyuan 40210590
