### ISSUE TITLE
DmGuard 大漠防护盾参数类型错误

### ISSUE THREAD

**Issue by bf21** [qianniancn/go-dmsoft#7]
![大漠防护盾参数类型错误](https://user-images.githubusercontent.com/93150640/138739427-4eb8dffd-488b-45f5-9f7e-72c8b8c44a34.png)
![文档手册](https://user-images.githubusercontent.com/93150640/138739664-3fbfa97f-cf0c-4b5e-b61a-553da4e26d45.png)

**Comment by qianniancn** [comment]
好的，已经修改了
